"""Synthetic tests for compute_array_prs and coverage tiers (no network).

Tests cover:
- Coverage tier classification at boundary conditions
- Full array scoring chain: normalize → score → ArrayPRSResult
- MAF fill integration via array scoring
- LD-proxy integration via array scoring
"""

from pathlib import Path

import polars as pl
import pytest

from just_prs.arrays import normalize_array
from just_prs.models import ArrayPRSResult, classify_coverage_tier, COVERAGE_TIERS

# Reuse synthetic 23andMe data from test_arrays
_23ANDME = """\
# This data file generated by 23andMe at: example
# rsid\tchromosome\tposition\tgenotype
rs100\t1\t1000\tAG
rs200\t1\t2000\tGG
rs300\t2\t3000\tAA
rs400\t2\t4000\t--
rs500\tX\t5000\tCT
"""


class TestCoverageTiers:
    """Test coverage tier classification at boundary conditions."""

    def test_reliable_at_boundary(self) -> None:
        assert classify_coverage_tier(0.90) == "reliable"

    def test_reliable_above(self) -> None:
        assert classify_coverage_tier(0.95) == "reliable"

    def test_usable_at_boundary(self) -> None:
        assert classify_coverage_tier(0.60) == "usable"

    def test_usable_just_below_reliable(self) -> None:
        assert classify_coverage_tier(0.89) == "usable"

    def test_low_at_boundary(self) -> None:
        assert classify_coverage_tier(0.40) == "low"

    def test_low_just_below_usable(self) -> None:
        assert classify_coverage_tier(0.59) == "low"

    def test_unreliable_below_low(self) -> None:
        assert classify_coverage_tier(0.39) == "unreliable"

    def test_unreliable_zero(self) -> None:
        assert classify_coverage_tier(0.0) == "unreliable"

    def test_reliable_perfect(self) -> None:
        assert classify_coverage_tier(1.0) == "reliable"

    def test_tier_thresholds_descending(self) -> None:
        thresholds = list(COVERAGE_TIERS.values())
        assert thresholds == sorted(thresholds, reverse=True)


class TestArrayPRSResultModel:
    """Test ArrayPRSResult model construction."""

    def test_defaults(self) -> None:
        r = ArrayPRSResult(pgs_id="PGS000001", score=1.5, variants_total=100, variants_matched=50, match_rate=0.5)
        assert r.chip == ""
        assert r.coverage_ratio == 0.0
        assert r.variants_proxied == 0
        assert r.effective_coverage == 0.0
        assert r.coverage_tier == "unreliable"
        assert r.proxy_r2_mean is None
        assert r.score_uncorrected == 0.0

    def test_full_construction(self) -> None:
        r = ArrayPRSResult(
            pgs_id="PGS000001",
            score=2.5,
            match_rate=0.80,
            variants_total=1000,
            variants_matched=800,
            variants_maf_filled=100,
            chip="gsa_v3",
            coverage_ratio=0.70,
            variants_proxied=50,
            effective_coverage=0.92,
            coverage_tier="reliable",
            proxy_r2_mean=0.88,
            score_uncorrected=2.3,
        )
        assert r.chip == "gsa_v3"
        assert r.coverage_tier == "reliable"
        assert r.proxy_r2_mean == pytest.approx(0.88)


class TestArrayScoringChain:
    """Test array scoring from normalize through to result."""

    def test_basic_array_score(self, tmp_path: Path) -> None:
        """Score a synthetic array without LD-proxy (no table available)."""
        src = tmp_path / "genome.txt"
        src.write_text(_23ANDME)
        norm = normalize_array(src, tmp_path / "norm.parquet", genome_build="GRCh37")

        scoring_lf = pl.DataFrame({
            "rsID": ["rs100", "rs200", "rs300"],
            "hm_chr": ["1", "1", "2"],
            "hm_pos": [1000, 2000, 3000],
            "effect_allele": ["G", "G", "A"],
            "other_allele": ["A", "A", "G"],
            "effect_weight": [1.0, 2.0, 0.5],
        }).lazy()

        from just_prs.prs import compute_prs

        result = compute_prs(
            vcf_path="",
            scoring_file=scoring_lf,
            genome_build="GRCh37",
            cache_dir=tmp_path,
            pgs_id="PGSTEST",
            genotypes_lf=pl.scan_parquet(norm),
        )
        assert result.variants_matched == 3
        assert result.score == pytest.approx(6.0)

    def test_maf_fill_integration(self, tmp_path: Path) -> None:
        """MAF fill recovers absent variants that have allelefrequency_effect."""
        src = tmp_path / "genome.txt"
        src.write_text(_23ANDME)
        norm = normalize_array(src, tmp_path / "norm.parquet", genome_build="GRCh37")

        scoring_lf = pl.DataFrame({
            "rsID": ["rs100", "rs_absent"],
            "hm_chr": ["1", "3"],
            "hm_pos": [1000, 9999],
            "effect_allele": ["G", "T"],
            "other_allele": ["A", "C"],
            "effect_weight": [1.0, 2.0],
            "allelefrequency_effect": [0.3, 0.25],
        }).lazy()

        from just_prs.prs import compute_prs

        result_no_maf = compute_prs(
            vcf_path="",
            scoring_file=scoring_lf,
            genome_build="GRCh37",
            cache_dir=tmp_path,
            pgs_id="TEST",
            genotypes_lf=pl.scan_parquet(norm),
            maf_fill=False,
        )

        result_maf = compute_prs(
            vcf_path="",
            scoring_file=scoring_lf,
            genome_build="GRCh37",
            cache_dir=tmp_path,
            pgs_id="TEST",
            genotypes_lf=pl.scan_parquet(norm),
            maf_fill=True,
        )

        assert result_maf.variants_maf_filled == 1
        assert result_no_maf.variants_maf_filled == 0
        expected_maf_contribution = 2.0 * (2 * 0.25)
        assert result_maf.score == pytest.approx(result_no_maf.score + expected_maf_contribution)

    def test_maf_fill_duckdb_engine(self, tmp_path: Path) -> None:
        """MAF fill works with DuckDB engine too."""
        src = tmp_path / "genome.txt"
        src.write_text(_23ANDME)
        norm = normalize_array(src, tmp_path / "norm.parquet", genome_build="GRCh37")

        scoring_lf = pl.DataFrame({
            "rsID": ["rs100", "rs_absent"],
            "hm_chr": ["1", "3"],
            "hm_pos": [1000, 9999],
            "effect_allele": ["G", "T"],
            "other_allele": ["A", "C"],
            "effect_weight": [1.0, 2.0],
            "allelefrequency_effect": [0.3, 0.25],
        }).lazy()

        from just_prs.prs import compute_prs_duckdb

        result = compute_prs_duckdb(
            vcf_path="",
            scoring_file=scoring_lf,
            genome_build="GRCh37",
            cache_dir=tmp_path,
            pgs_id="TEST",
            genotypes_lf=pl.scan_parquet(norm),
            genotypes_parquet=str(norm),
            maf_fill=True,
        )

        assert result.variants_maf_filled == 1
        expected_maf_contribution = 2.0 * (2 * 0.25)
        assert result.score > 0

    def test_chip_detection_from_normalized(self, tmp_path: Path) -> None:
        """Chip detection works on a normalized array parquet."""
        src = tmp_path / "genome.txt"
        src.write_text(_23ANDME)
        norm = normalize_array(src, tmp_path / "norm.parquet")

        from just_prs.arrays import detect_chip_generation
        chip = detect_chip_generation(norm)
        assert chip.marker_count == 4
        assert chip.chip_id in ("gsa_v3", "omniexpress")
