"""GRCh37 array → GRCh38 liftover bridge tests.

The core tests are network-light (only the ~3 MB UCSC chain auto-downloads) and
use dbSNP/UCSC-verified coordinate pairs as ground truth. The full
``compute_array_prs(target_build=...)`` path is opt-in (env-gated) because it
pulls the 67 MB GSA A1 manifest and the reference-allele universe.
"""

from __future__ import annotations

import os
from pathlib import Path

import polars as pl
import pytest

from just_prs.arrays import normalize_array
from just_prs.liftover import lift_frame
from just_prs.prs import compute_prs, compute_prs_duckdb

# rs429358 (APOE):  GRCh37 19:45411941 -> GRCh38 19:44908684
# rs7412   (APOE):  GRCh37 19:45412079 -> GRCh38 19:44908822
# rs1815739 (ACTN3): GRCh37 11:66328095 -> GRCh38 11:66560624
_ARRAY_GRCH37 = """\
# This data file generated by 23andMe
# rsid\tchromosome\tposition\tgenotype
rs429358\t19\t45411941\tAG
rs7412\t19\t45412079\tCC
rs1815739\t11\t66328095\tTT
"""

# Scoring file in GRCh38 at the LIFTED positions. Expected score after lifting:
#   rs429358  het (A/G), effect G -> dosage 1 * 1.0 = 1.0
#   rs7412    hom (C/C), effect T -> dosage 0 * 2.0 = 0.0
#   rs1815739 hom (T/T), effect T -> dosage 2 * 0.5 = 1.0
# total = 2.0
_SCORING_GRCH38 = pl.DataFrame(
    {
        "rsID": ["rs429358", "rs7412", "rs1815739"],
        "hm_chr": ["19", "19", "11"],
        "hm_pos": [44908684, 44908822, 66560624],
        "effect_allele": ["G", "T", "T"],
        "other_allele": ["A", "C", "C"],
        "effect_weight": [1.0, 2.0, 0.5],
    }
)
_EXPECTED_SCORE = 2.0


def _normalized_grch37_array(tmp_path: Path) -> Path:
    src = tmp_path / "genome.txt"
    src.write_text(_ARRAY_GRCH37)
    return normalize_array(src, tmp_path / "norm.parquet", genome_build="GRCh37")


def test_grch37_array_vs_grch38_scoring_is_the_silent_deadend(tmp_path: Path) -> None:
    """Unlifted GRCh37 genotypes against GRCh38 scoring match nothing (the bug)."""
    norm = _normalized_grch37_array(tmp_path)
    result = compute_prs(
        vcf_path="",
        scoring_file=_SCORING_GRCH38.lazy(),
        genome_build="GRCh38",
        cache_dir=tmp_path,
        pgs_id="T",
        genotypes_lf=pl.scan_parquet(norm),
    )
    assert result.variants_matched == 0
    assert result.score == pytest.approx(0.0)


@pytest.mark.parametrize("engine", ["polars", "duckdb"])
def test_lift_then_score_recovers_all_variants(tmp_path: Path, engine: str) -> None:
    """Lifting the genotypes 37→38 recovers the matches and the correct score."""
    norm = _normalized_grch37_array(tmp_path)
    lifted, dropped = lift_frame(pl.read_parquet(norm), "GRCh37", "GRCh38")
    assert dropped.height == 0
    lifted_path = tmp_path / "lifted.parquet"
    lifted.write_parquet(lifted_path)

    if engine == "duckdb":
        result = compute_prs_duckdb(
            vcf_path="",
            scoring_file=_SCORING_GRCH38.lazy(),
            genome_build="GRCh38",
            cache_dir=tmp_path,
            pgs_id="T",
            genotypes_lf=pl.scan_parquet(lifted_path),
            genotypes_parquet=str(lifted_path),
        )
    else:
        result = compute_prs(
            vcf_path="",
            scoring_file=_SCORING_GRCH38.lazy(),
            genome_build="GRCh38",
            cache_dir=tmp_path,
            pgs_id="T",
            genotypes_lf=pl.scan_parquet(lifted_path),
        )
    assert result.variants_matched == 3
    assert result.score == pytest.approx(_EXPECTED_SCORE)


def test_lift_dropped_locus_is_absent_from_lifted_set(tmp_path: Path) -> None:
    """A position that fails to lift is dropped — so it can never enter a lifted
    restoration scope and be assumed hom-ref in the target build."""
    positions = pl.DataFrame(
        {
            "chr_norm": ["19", "1"],
            "pos": [45411941, 10**12],  # second is beyond any real contig -> unmapped
        }
    )
    lifted, dropped = lift_frame(positions, "GRCh37", "GRCh38", chrom_col="chr_norm")
    assert lifted.height == 1
    assert lifted["pos"].to_list() == [44908684]
    assert dropped.height == 1
    assert dropped["liftover_reason"].to_list() == ["unmapped"]


def test_sample_build_mismatch_raises(tmp_path: Path) -> None:
    """B2: a known sample build that differs from the scoring build fails loudly
    instead of silently scoring ~0 variants."""
    norm = _normalized_grch37_array(tmp_path)
    with pytest.raises(ValueError, match="(?i)build.*mismatch"):
        compute_prs(
            vcf_path="",
            scoring_file=_SCORING_GRCH38.lazy(),
            genome_build="GRCh38",
            cache_dir=tmp_path,
            pgs_id="T",
            genotypes_lf=pl.scan_parquet(norm),
            sample_build="GRCh37",
        )


def test_sample_build_match_alias_ok(tmp_path: Path) -> None:
    """A matching sample build (via alias normalization) does not raise."""
    norm = _normalized_grch37_array(tmp_path)
    lifted, _ = lift_frame(pl.read_parquet(norm), "GRCh37", "GRCh38")
    lifted_path = tmp_path / "lifted.parquet"
    lifted.write_parquet(lifted_path)
    result = compute_prs(
        vcf_path="",
        scoring_file=_SCORING_GRCH38.lazy(),
        genome_build="GRCh38",
        cache_dir=tmp_path,
        pgs_id="T",
        genotypes_lf=pl.scan_parquet(lifted_path),
        sample_build="hg38",  # alias of GRCh38 -> no mismatch
    )
    assert result.variants_matched == 3


@pytest.mark.skipif(
    os.environ.get("JUST_PRS_TEST_ARRAY_LIFT_E2E") != "1",
    reason="set JUST_PRS_TEST_ARRAY_LIFT_E2E=1 to run the full bridge (pulls 67 MB GSA A1 manifest + universe)",
)
def test_compute_array_prs_target_build_end_to_end(tmp_path: Path) -> None:
    """Full bridge through compute_array_prs(target_build='GRCh38')."""
    from just_prs.array_scoring import compute_array_prs

    src = tmp_path / "genome.txt"
    src.write_text(_ARRAY_GRCH37)
    result = compute_array_prs(
        array_path=src,
        scoring_file=_SCORING_GRCH38.lazy(),
        genome_build="GRCh37",
        target_build="GRCh38",
        cache_dir=tmp_path,
        pgs_id="T",
        ld_proxy=False,
        maf_fill=False,
    )
    assert result.source_build == "GRCh37"
    assert result.lifted_to_build == "GRCh38"
    assert result.variants_matched == 3
    assert result.score == pytest.approx(_EXPECTED_SCORE)
