"""Deterministic tests for consumer-array ingestion (normalize_array).

Uses synthetic 23andMe / AncestryDNA raw files with hand-constructed genotypes
so every expected value (dosage, match) is known exactly — no network, no cache.
"""

import gzip
import os
from pathlib import Path

import polars as pl
import pytest

from just_prs.arrays import detect_array_format, normalize_array
from just_prs.prs import compute_prs

# A tiny 23andMe export: het, hom-alt, hom-ref, no-call, and a chrX letter chrom.
_23ANDME = """\
# This data file generated by 23andMe at: example
# rsid\tchromosome\tposition\tgenotype
rs100\t1\t1000\tAG
rs200\t1\t2000\tGG
rs300\t2\t3000\tAA
rs400\t2\t4000\t--
rs500\tX\t5000\tCT
"""

# Same five markers in AncestryDNA layout (numeric chrom 23 == X, two allele cols).
_ANCESTRY = """\
#AncestryDNA raw data download
rsid\tchromosome\tposition\tallele1\tallele2
rs100\t1\t1000\tA\tG
rs200\t1\t2000\tG\tG
rs300\t2\t3000\tA\tA
rs400\t2\t4000\t0\t0
rs500\t23\t5000\tC\tT
"""

# Same five markers in MyHeritage layout: comma-CSV, quoted, RESULT = the call.
# (FamilyTreeDNA ships the identical RSID,CHROMOSOME,POSITION,RESULT format.)
_MYHERITAGE = """\
# MyHeritage DNA raw data. For more info see www.myheritage.com
RSID,CHROMOSOME,POSITION,RESULT
"rs100","1","1000","AG"
"rs200","1","2000","GG"
"rs300","2","3000","AA"
"rs400","2","4000","--"
"rs500","X","5000","CT"
"""

# A bare FamilyTreeDNA-style CSV (no vendor name in header) — detected by shape.
_FTDNA_BARE = """\
RSID,CHROMOSOME,POSITION,RESULT
"rs100","1","1000","AG"
"rs200","1","2000","GG"
"""


def test_detect_format() -> None:
    assert detect_array_format(_23ANDME) == "23andme"
    assert detect_array_format(_ANCESTRY) == "ancestrydna"
    assert detect_array_format(_MYHERITAGE) == "myheritage"
    # Bare CSV with no vendor name → detected by comma delimiter (FTDNA family).
    assert detect_array_format(_FTDNA_BARE) == "myheritage"


def test_myheritage_matches_23andme(tmp_path: Path) -> None:
    """MyHeritage comma-CSV normalizes identically to the 23andMe TSV layout."""
    a = normalize_array(_write(tmp_path / "23.txt", _23ANDME), tmp_path / "a.parquet")
    m = normalize_array(_write(tmp_path / "mh.csv", _MYHERITAGE), tmp_path / "m.parquet")
    da = pl.read_parquet(a).sort("pos")
    dm = pl.read_parquet(m).sort("pos")
    assert da.select("chrom", "pos", "rsid", "GT", "genotype").equals(
        dm.select("chrom", "pos", "rsid", "GT", "genotype")
    )


def test_23andme_normalization(tmp_path: Path) -> None:
    src = tmp_path / "genome.txt"
    src.write_text(_23ANDME)
    out = normalize_array(src, tmp_path / "norm.parquet")
    df = pl.read_parquet(out).sort("pos")

    # No-call (rs400) dropped; 4 mapped calls remain.
    assert df.height == 4
    assert df["rsid"].to_list() == ["rs100", "rs200", "rs300", "rs500"]
    assert set(df.columns) == {"chrom", "pos", "rsid", "ref", "alt", "GT", "genotype"}

    by_rsid = {r["rsid"]: r for r in df.iter_rows(named=True)}
    # Heterozygous AG → 0/1, observed alleles sorted.
    assert by_rsid["rs100"]["GT"] == "0/1"
    assert by_rsid["rs100"]["genotype"] == ["A", "G"]
    # Homozygous GG → 1/1 with ref==alt==G.
    assert by_rsid["rs200"]["GT"] == "1/1"
    assert by_rsid["rs200"]["ref"] == "G" and by_rsid["rs200"]["alt"] == "G"
    # chrX preserved as letter.
    assert by_rsid["rs500"]["chrom"] == "X"


def test_ancestry_matches_23andme(tmp_path: Path) -> None:
    """The two vendor layouts of the same genotypes normalize identically."""
    a = normalize_array(_write(tmp_path / "23.txt", _23ANDME), tmp_path / "a.parquet")
    b = normalize_array(_write(tmp_path / "anc.txt", _ANCESTRY), tmp_path / "b.parquet")
    da = pl.read_parquet(a).sort("pos")
    db = pl.read_parquet(b).sort("pos")
    # AncestryDNA numeric chrom 23 must have been mapped to X to match 23andMe.
    assert da.select("chrom", "pos", "GT", "genotype").equals(
        db.select("chrom", "pos", "GT", "genotype")
    )


def test_gzip_input(tmp_path: Path) -> None:
    src = tmp_path / "genome.txt.gz"
    with gzip.open(src, "wt") as f:
        f.write(_23ANDME)
    df = pl.read_parquet(normalize_array(src, tmp_path / "g.parquet"))
    assert df.height == 4


def test_dosage_via_compute_prs(tmp_path: Path) -> None:
    """Drive a hand-built scoring file through compute_prs against the array parquet.

    Expected score, given effect weights and the known genotypes:
      rs100 AG, effect=G, w=1.0  → dosage 1 → +1.0
      rs200 GG, effect=G, w=2.0  → dosage 2 → +4.0
      rs300 AA, effect=A, w=0.5  → dosage 2 → +1.0
      rs500 CT, effect=A, w=3.0  → dosage 0 → +0.0  (effect allele absent)
    Total = 6.0 over 4 matched variants.
    """
    geno = normalize_array(_write(tmp_path / "g.txt", _23ANDME), tmp_path / "g.parquet")

    scoring = pl.DataFrame({
        "rsID": ["rs100", "rs200", "rs300", "rs500"],
        "hm_chr": ["1", "1", "2", "X"],
        "hm_pos": [1000, 2000, 3000, 5000],
        "effect_allele": ["G", "G", "A", "A"],
        "other_allele": ["A", "A", "G", "C"],
        "effect_weight": [1.0, 2.0, 0.5, 3.0],
    }).lazy()

    result = compute_prs(
        vcf_path="",
        scoring_file=scoring,
        genome_build="GRCh37",
        cache_dir=tmp_path,
        pgs_id="PGSTEST",
        genotypes_lf=pl.scan_parquet(geno),
    )
    assert result.variants_matched == 4
    assert result.variants_total == 4
    assert result.score == pytest.approx(6.0)


def _write(path: Path, text: str) -> Path:
    path.write_text(text)
    return path


# ---------------------------------------------------------------------------
# Real consumer-array file (opt-in): set PRS_TEST_ARRAY_FILE to a real 23andMe /
# AncestryDNA / openSNP download (.txt / .txt.gz / .zip). Validates that a real
# vendor file ingests cleanly and that its typed positions overlap the GSA
# coverage manifest heavily — cross-checking the coverage map against ground truth.
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not os.environ.get("PRS_TEST_ARRAY_FILE"),
    reason="set PRS_TEST_ARRAY_FILE to a real 23andMe/AncestryDNA/openSNP file to run",
)
def test_real_array_file_overlaps_gsa_manifest(tmp_path: Path) -> None:
    from just_prs.chip_coverage import chip_typed_positions
    from just_prs.scoring import resolve_cache_dir

    src = Path(os.environ["PRS_TEST_ARRAY_FILE"])
    assert src.exists(), f"PRS_TEST_ARRAY_FILE does not exist: {src}"

    out = normalize_array(src, tmp_path / "real.parquet")
    geno = pl.read_parquet(out)
    # Real consumer chips type hundreds of thousands of markers.
    assert geno.height > 100_000
    assert set(geno.columns) == {"chrom", "pos", "rsid", "ref", "alt", "GT", "genotype"}

    # Cross-validate against the GSA coverage manifest: a real GSA-based file
    # should have the large majority of its calls on GSA-typed positions.
    typed = chip_typed_positions("gsa_v3", resolve_cache_dir())
    norm_pos = geno.select(
        pl.col("chrom").alias("chr_norm"), pl.col("pos")
    )
    overlap = norm_pos.join(typed, on=["chr_norm", "pos"], how="inner").height
    overlap_frac = overlap / geno.height
    # GSA-based files (23andMe v5, AncestryDNA v2, MyHeritage, FTDNA, LivingDNA)
    # should overlap heavily; older OmniExpress chips will overlap less.
    assert overlap_frac >= 0.50, f"Only {overlap_frac:.1%} of calls on GSA positions"
